### ISSUE TITLE
Zemberek XMLHttpRequest error.

### ISSUE THREAD

**Issue by ruwiss** [CidQu/sozluk#3]
**Zemberek Çalışmıyor**
Paket içerisindeki ip adresi şuan için kullanılamıyor. Bu nedenle veriyi alamıyorum. Güncellenebilir mi?

**Comment by CidQu** [comment]
Sunucuda olan bakım sebebiyle 1 küsür haftadır kapalı.

Zemberek tamamen portlanana kadar böyle bir yöntem izlemiştim.

Sunucuları bugün/yarın güncelleyeceğim. Hatırlattığınız için teşekkürler!

**Comment by CidQu** [comment]
#4 üzerinde yapılan çalışma ile bu hafta içerisinde düzeltilecek.
