### ISSUE TITLE
Connection closed before full header was received

### ISSUE THREAD

**Issue by abdullahh2** [CidQu/sozluk#4]
**Flutter doctor**
√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2486], locale tr-TR)
    • Flutter version 3.3.10 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1) 
    • Android SDK at C:\Users\siirt\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\siirt\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\siirt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.55

[√] HTTP Host Availability
    • All required HTTP hosts are available
    
   
API'yi kendim de denedim olmadı. Node.js ile aynı endpoint'e get isteği atıyorum verileri çekiyor, python ile denedim yine çekiyor. Dart ile deniyorum, fakat çekmiyor. Dio denedim, http denedim yok yine hata. En son bu paketi buldum baktım bu paaket de aynı işi yapıyor ama paket de aynı hatayı veriyor. Belki projede sıkıntı var dedim, sıfır bir proje açtım yok onda da aynı hata. Dart projesi için lazım, SDK olarak Flutter yazıyor. Ondan kaynaklı olabilir mi? Yoksa alakası yok mu?

**Comment by CidQu** [comment]
Onunla alakası yoktur, yazdığınız kodu gönderebilir misiniz? İncelemek isterim.

**Comment by abdullahh2** [comment]
import 'package:sozluk/birlesim.dart';

void main(List<String> arguments) async {
  final sozluk = Sozluk().dictionary;

  var ans = await sozluk.meaning("Merhaba");

  print("Anlam: $ans");
}


Ekstra hiçbir şey yazmadım hocam. Kodu atmadan önce de denedim sonuç aynı.

Ekran Görüntüsü:
![image](https://user-images.githubusercontent.com/48069196/213875951-e8583305-dac4-4ae7-8ca0-353f3ebeedda.png)

**Comment by CidQu** [comment]
Uzun süre mesaj yazamadığım için kusura bakmayın, dünyevi işlerimi halletmek ile meşguldüm. Bu hafta içerisinde yeni bir güncelleme paylaşacağım. Hem paketteki ip'leri yeni ipler ile değiştireceğim hem de insanların kendi iplerini girmesine olanak tanıyacak bir sistem geliştireceğim.

**Comment by abdullahh2** [comment]
Tamamdır, güncellemeyi bekleyeceğim. Sorun çözülünce konuyu çözüldü olarak kapatırım. Şimdiden ellerine sağlık. Kolay gelsin hocam.

**Comment by CidQu** [comment]
Düzelttim, bir deneyebilir misin? Sunucuları yeniledim ve bir sürü hata düzeltmesi yaptım. Ekstra kendi ip'ni girmene gerek kalmadan kullanabilmen gerek.

**Comment by CidQu** [comment]
Son sürümü kullandığındanızdan emin olun

https://pub.dev/packages/sozluk
sozluk: ^2.3.0

**Comment by CidQu** [comment]
Sorun çözüldüğü için ve @abdullahh2 cevap vermediği için kapattım. Sorun devam ederse yeniden açarsınız.
